name: start instance and cocker

on:
  schedule:
    - cron: '30 4 * * 1-5' 
  workflow_dispatch:

jobs:
  start:
    runs-on: ubuntu-latest

    steps:
      - name: Start EC2
        run: |
          aws ec2 start-instances --instance-ids ${{ secrets.EC2_INSTANCE_ID }} --region ${{ secrets.AWS_REGION }}
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Wait for EC2 to be in running state
        run: |
          for i in {1..30}; do
            state=$(aws ec2 describe-instances \
              --instance-ids ${{ secrets.EC2_INSTANCE_ID }} \
              --region ${{ secrets.AWS_REGION }} \
              --query "Reservations[0].Instances[0].State.Name" \
              --output text)
            echo "EC2 state: $state"
            if [ "$state" = "running" ]; then break; fi
            sleep 10
          done
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Get Public IP
        id: get_ip
        run: |
          IP=$(aws ec2 describe-instances \
            --instance-ids ${{ secrets.EC2_INSTANCE_ID }} \
            --region ${{ secrets.AWS_REGION }} \
            --query "Reservations[0].Instances[0].PublicIpAddress" \
            --output text)
          echo "::add-mask::$IP"
          echo "ec2_ip=$IP" >> "$GITHUB_OUTPUT"
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Wait for SSH port (22) to be ready
        run: |
          for i in {1..10}; do
            nc -zv ${{ steps.get_ip.outputs.ec2_ip }} 22 && break
            echo "Waiting for SSH..."
            sleep 10
          done

      - name: Start Docker container
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ steps.get_ip.outputs.ec2_ip }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            docker ps -a --format '{{.Names}}' | grep -q '^my_container_name$' && \
              docker start my_container_name || \
              docker run -d --name my_container_name my_image
